# Generated by Django 3.1.6 on 2021-03-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sessionyearmodel',
            managers=[
            ],
        ),
    ]
