# Generated by Django 3.1.6 on 2021-03-08 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20210308_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.attendance'),
        ),
    ]
